apiVersion: 1

datasources:
  - name: influxdb-telegraf
    type: influxdb
    access: proxy
    database: telegraf
    user: admin
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      timeInterval: "10s"
    secureJsonData:
      password: $INFLUXDB_ADMIN_PASSWORD